# -*- restclient -*-
#
# Gets  all Github APIs, formats JSON, shows response status and headers underneath.
# Also sends a User-Agent header, because the Github API requires this.
#
GET http://localhost:8080/items

#
POST http://localhost:8080/items
Content-Type: application/json
{
  "name" : "special-item-name-1",
  "desc": "special-item-name-description-1"
}
#
POST http://localhost:8080/items
Content-Type: application/json
{
  "name" : "special-item-name-2",
  "desc": "special-item-name-description-2"
}

#
DELETE http://localhost:8080/items/1
#
DELETE http://localhost:8080/items/2
